### ISSUE TITLE
What is the sense of k in dot product?

### ISSUE THREAD

**Issue by keyblade95** [bogliosimone/similaripy#1]
Reading the example in the readme:
```python
import similaripy as sim
import scipy.sparse as sps

# create a random user-rating matrix (URM)
urm = sps.random(1000, 2000, density=0.025)

# train the model with 50 knn per item 
model = sim.cosine(urm.T, k=50)

# recommend 100 items to users 1, 14 and 8
user_recommendations = sim.dot_product(urm, model, target_rows=[1,14,8], k=100)
```
I have a doubt in the usage of the k param on the last row.. What is its sense?
Can I use the dot product as the standard dot product between 2 matrices? Can you clarify this please?

**Comment by bogliosimone** [comment]
hi,
the parameter k is the number of the nearest neighbors per row in the computation (in this case, for a simple dot product, the top k values are the highest k values per row computed in the matrices product)

if you need the standard dot product with **all** elements in the result you could just set k=urm.shape[0] (row length) but keep in mind that in this case you obtain as result dense rows with lot of zeros (so, depending on the size and density of the dataset, it could require a certain amount of memory, also you lose the advantage of using sparse matrices)

**Comment by keyblade95** [comment]
Yep, I was doing exactly how you suggested!
So, in this case, do you think that I should use simply the [dot function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.dot.html) of csr matrices? Will it be faster?

**Comment by keyblade95** [comment]
Thank you so much!!

**Comment by bogliosimone** [comment]
You are welcome :)

If you found my work useful, you could leave me a star, thanks :)

**Comment by keyblade95** [comment]
I'm a student at Polimi and your work help me so much for the Rec Sys course :)
