### ISSUE TITLE
Incorporate Weighted Jaccard Similarity

### ISSUE THREAD

**Issue by JnaneshPrabhu** [bogliosimone/similaripy#3]
Hi Simone,
This is a great library and would be very helpful in one of our projects. The ask is can we incoporate weighted Jaccard Similairity in the library?
Or is there in general any library you guys might know off which we can utilise to find weighted jaccard similairity of close to 3lakh rows?
Thanks in advance.

**Comment by bogliosimone** [comment]
Hi Jnanesh,
sorry for the very late response.

I had a look a the formula of the weighted Jaccard similarity and it cannot be easy integrated in the existing code, it would require writing a lot of new code. 

Unfortunately at this moment I don't have time to add new features to the library.
However I am glad that my work has been useful to your project 😄 

Thanks,
Simone
